DECLARE @CPF VARCHAR(14), @COUNT INT, @SOMA INT, @RESTO_DIGITO INT, @DIGITO INT, @NUM CHAR(2), @NUM_VERIFICADOR VARCHAR(2)
SET @CPF = '222.333.666-38'
SET @COUNT = 11
SET @SOMA = 0

SET @CPF = REPLACE(@CPF, '.', '')
SET @CPF = REPLACE(@CPF, '-', '')

-- Verificando se o cpf é composto de somente um algarismo e calculando número verificador

IF(SUBSTRING(@CPF,1,10) != SUBSTRING(@CPF,2,11))
BEGIN
  SET @NUM = SUBSTRING(@CPF,10 ,11)
  SET @CPF = SUBSTRING(@CPF,1 ,9)

  WHILE(2 <= @COUNT)
  BEGIN
  
  SET @SOMA = @SOMA  + (@COUNT * CONVERT(INT, SUBSTRING(@CPF,11 - @COUNT ,1)))
  SET @COUNT = @COUNT - 1;

  END

  SET @RESTO_DIGITO = (@SOMA % 11)

  IF(2 <= @RESTO_DIGITO)
  BEGIN
  SET @DIGITO = 11 - @RESTO_DIGITO
  END
  ELSE
  BEGIN
  SET @DIGITO = 0
  END

  SET @CPF = @CPF + CONVERT(CHAR(1), @DIGITO)

  SET @NUM_VERIFICADOR = CONVERT(CHAR(1), @DIGITO)

  SET @COUNT = 11

  SET @SOMA = 0

  WHILE(2 <= @COUNT)
  BEGIN

  SET @SOMA = @SOMA  + (@COUNT * CONVERT(INT, SUBSTRING(@CPF,11 - (@COUNT-1) ,1)))
  SET @COUNT = @COUNT - 1;

  END

  SET @RESTO_DIGITO = (@SOMA % 11)

  IF(2 <= @RESTO_DIGITO)
  BEGIN
  SET @DIGITO = 11 - @RESTO_DIGITO
  END
  ELSE
  BEGIN
  SET @DIGITO = 0
  END


-- Verificando se o codigo verificador é válido

  SET @NUM_VERIFICADOR =  @NUM_VERIFICADOR + CONVERT(CHAR(1), @DIGITO)

  IF(@NUM_VERIFICADOR = @NUM)
  BEGIN
  PRINT 'O CPF � V�LIDO.'
  END
  ELSE
  BEGIN 
  PRINT 'O CPF � INV�LIDO.'
  END
END
ELSE
BEGIN
  PRINT 'O CPF S� TEM N�MEROS IGUAIS.'
END








